/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newlibrarymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhavesh
 */
public class EventLogFrame extends javax.swing.JFrame {

    MenuFrame mnfobj;
    /**
     * Creates new form EventLogFrame
     */
    public EventLogFrame(MenuFrame mnfobj) {
        initComponents();
        this.mnfobj = mnfobj;
        this.setLocationRelativeTo(null);
    }
    
    public String CBIndexToColName(int i){
        String colname=null;
    switch(i){
        case 0: colname = "octime";
        break;
        case 1: colname = "descr";
        break;
        case 2: colname = "cby";
        break;
    }
    return colname;
    }
    
    public void refresh(){
    String sfield1 = CBIndexToColName(SearchFieldCB1.getSelectedIndex());
    String sfield2 = CBIndexToColName(SearchFieldCB2.getSelectedIndex());
    String sfield3 = CBIndexToColName(SearchFieldCB3.getSelectedIndex());
    String scrit1 = (String)SearchCritCB1.getSelectedItem();
    String scrit2 = (String)SearchCritCB2.getSelectedItem();
    String scrit3 = (String)SearchCritCB3.getSelectedItem();
    String search1 = Newlibrarymanagementsystem.MysqlEscapeSeq(SearchTF1.getText());
    String search2 = Newlibrarymanagementsystem.MysqlEscapeSeq(SearchTF2.getText());
    String search3 = Newlibrarymanagementsystem.MysqlEscapeSeq(SearchTF3.getText());
    
    boolean inv1 = NOTCheck1.isSelected();
    boolean inv2 = NOTCheck2.isSelected();
    boolean inv3 = NOTCheck3.isSelected();
    String sorter = CBIndexToColName(SortCB.getSelectedIndex());
    boolean sortdesc = SortDescCheck.isSelected();
    String query = "SELECT octime,descr,cby FROM evl WHERE "+(inv1 ? "NOT " : "")+sfield1+" "+(scrit1.length()==1 ? scrit1 : "LIKE")+" \'"+(scrit1=="ends with" || scrit1=="includes" ? "%" : "")+search1+(scrit1=="starts with" || scrit1=="includes" ? "%" : "")+"\' AND "+(inv2 ? "NOT " : "")+sfield2+" "+(scrit2.length()==1 ? scrit2 : "LIKE")+" \'"+(scrit2=="ends with" || scrit2=="includes" ? "%" : "")+search2+(scrit2=="starts with" || scrit2=="includes" ? "%" : "")+"\' AND "+(inv3 ? "NOT " : "")+sfield3+" "+(scrit3.length()==1 ? scrit3 : "LIKE")+" \'"+(scrit3=="ends with" || scrit3=="includes" ? "%" : "")+search3+(scrit3=="starts with" || scrit3=="includes" ? "%" : "")+"\' ORDER BY "+sorter+(sortdesc ? " DESC " : " ")+";" ;
    DefaultTableModel model = (DefaultTableModel)Tbl.getModel();
    int rows = model.getRowCount();
    if(rows!=0)
        for(int i=0 ; i<rows ; i++)
            model.removeRow(0);
    try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
    ResultSet rs = stmt.executeQuery(query);
    Object[] tuple = new Object[3];
    while(rs.next()){
    for(int i=1 ; i<=3; i++)
    tuple[i-1] = rs.getObject(i);
    model.addRow(tuple);
    }
    rs.close();
    stmt.close();
    c.close();
    }
    catch(Exception e){
        System.out.println(e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        SortCB = new javax.swing.JComboBox<>();
        SortDescCheck = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchTF1 = new javax.swing.JTextField();
        SearchCritCB1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        SearchCritCB2 = new javax.swing.JComboBox<>();
        SearchTF2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SearchCritCB3 = new javax.swing.JComboBox<>();
        SearchTF3 = new javax.swing.JTextField();
        NOTCheck1 = new javax.swing.JCheckBox();
        NOTCheck2 = new javax.swing.JCheckBox();
        NOTCheck3 = new javax.swing.JCheckBox();
        SearchFieldCB1 = new javax.swing.JComboBox<>();
        SearchFieldCB2 = new javax.swing.JComboBox<>();
        SearchFieldCB3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Event Log");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        SortCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Occurence time", "Description", "Caused by" }));
        SortCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SortCBItemStateChanged(evt);
            }
        });

        SortDescCheck.setSelected(true);
        SortDescCheck.setText("in descending order");
        SortDescCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SortDescCheckItemStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Criteria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("1");

        SearchTF1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                SearchTF1CaretUpdate(evt);
            }
        });

        SearchCritCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "starts with", "ends with", "includes" }));
        SearchCritCB1.setSelectedItem("starts with");
        SearchCritCB1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchCritCB1ItemStateChanged(evt);
            }
        });

        jLabel2.setText("2");

        SearchCritCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "starts with", "ends with", "includes" }));
        SearchCritCB2.setSelectedItem("starts with");
        SearchCritCB2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchCritCB2ItemStateChanged(evt);
            }
        });

        SearchTF2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                SearchTF2CaretUpdate(evt);
            }
        });

        jLabel6.setText("3");

        SearchCritCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "starts with", "ends with", "includes" }));
        SearchCritCB3.setSelectedItem("starts with");
        SearchCritCB3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchCritCB3ItemStateChanged(evt);
            }
        });

        SearchTF3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                SearchTF3CaretUpdate(evt);
            }
        });

        NOTCheck1.setText("NOT");
        NOTCheck1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NOTCheck1ItemStateChanged(evt);
            }
        });

        NOTCheck2.setText("NOT");
        NOTCheck2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NOTCheck2ItemStateChanged(evt);
            }
        });

        NOTCheck3.setText("NOT");
        NOTCheck3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NOTCheck3ItemStateChanged(evt);
            }
        });

        SearchFieldCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Occurence time", "Description", "Caused by" }));
        SearchFieldCB1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchFieldCB1ItemStateChanged(evt);
            }
        });

        SearchFieldCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Occurence time", "Description", "Caused by" }));
        SearchFieldCB2.setSelectedItem("Description");
        SearchFieldCB2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchFieldCB2ItemStateChanged(evt);
            }
        });

        SearchFieldCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Occurence time", "Description", "Caused by" }));
        SearchFieldCB3.setSelectedItem("Caused by");
        SearchFieldCB3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchFieldCB3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchFieldCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchFieldCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NOTCheck2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NOTCheck1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchFieldCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NOTCheck3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchCritCB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCritCB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCritCB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchTF1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(SearchTF2)
                    .addComponent(SearchTF3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCritCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(NOTCheck1)
                    .addComponent(SearchFieldCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCritCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(NOTCheck2)
                    .addComponent(SearchFieldCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCritCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(NOTCheck3)
                    .addComponent(SearchFieldCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Sort By");

        Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Occurence time", "Description", "Caused by"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tbl.getTableHeader().setReorderingAllowed(false);
        Tbl.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(Tbl);
        if (Tbl.getColumnModel().getColumnCount() > 0) {
            Tbl.getColumnModel().getColumn(0).setPreferredWidth(150);
            Tbl.getColumnModel().getColumn(1).setPreferredWidth(500);
            Tbl.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(SortCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SortDescCheck))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SortCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(SortDescCheck)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        mnfobj.evlbtnen();
    }//GEN-LAST:event_formWindowClosed

    private void SortDescCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SortDescCheckItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SortDescCheckItemStateChanged

    private void SortCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SortCBItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SortCBItemStateChanged

    private void SearchTF1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_SearchTF1CaretUpdate
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchTF1CaretUpdate

    private void SearchTF2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_SearchTF2CaretUpdate
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchTF2CaretUpdate

    private void SearchTF3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_SearchTF3CaretUpdate
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchTF3CaretUpdate

    private void SearchCritCB1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchCritCB1ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchCritCB1ItemStateChanged

    private void SearchCritCB2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchCritCB2ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchCritCB2ItemStateChanged

    private void SearchCritCB3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchCritCB3ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchCritCB3ItemStateChanged

    private void NOTCheck1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NOTCheck1ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_NOTCheck1ItemStateChanged

    private void NOTCheck2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NOTCheck2ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_NOTCheck2ItemStateChanged

    private void NOTCheck3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NOTCheck3ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_NOTCheck3ItemStateChanged

    private void SearchFieldCB1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchFieldCB1ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchFieldCB1ItemStateChanged

    private void SearchFieldCB2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchFieldCB2ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchFieldCB2ItemStateChanged

    private void SearchFieldCB3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchFieldCB3ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchFieldCB3ItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventLogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventLogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventLogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventLogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox NOTCheck1;
    private javax.swing.JCheckBox NOTCheck2;
    private javax.swing.JCheckBox NOTCheck3;
    private javax.swing.JComboBox<String> SearchCritCB1;
    private javax.swing.JComboBox<String> SearchCritCB2;
    private javax.swing.JComboBox<String> SearchCritCB3;
    private javax.swing.JComboBox<String> SearchFieldCB1;
    private javax.swing.JComboBox<String> SearchFieldCB2;
    private javax.swing.JComboBox<String> SearchFieldCB3;
    private javax.swing.JTextField SearchTF1;
    private javax.swing.JTextField SearchTF2;
    private javax.swing.JTextField SearchTF3;
    private javax.swing.JComboBox<String> SortCB;
    private javax.swing.JCheckBox SortDescCheck;
    private javax.swing.JTable Tbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
