/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newlibrarymanagementsystem;

import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author bhavesh
 */
public class LoginFrame extends javax.swing.JFrame {

    int WrongPasswordCounter;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        ForgotPasswordBtn.setVisible(false);
        Frameset();
        WrongPasswordCounter = 0 ;
        pwdPF.requestFocus();
    }
    
    public void Frameset(){
    String query = "SELECT uname FROM accounts WHERE deleted = 'N' ORDER BY uname DESC ;" ;
    try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
    ResultSet rs = stmt.executeQuery(query);
    while(rs.next())
    unameCB.addItem(rs.getObject(1).toString());
    rs.close();
    stmt.close();
    c.close();
    }
    catch(Exception e){
        System.out.println(e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotPasswordDialog = new javax.swing.JDialog();
        secqLbl = new javax.swing.JLabel();
        secansTF = new javax.swing.JTextField();
        npwdPF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cnpwdPF = new javax.swing.JPasswordField();
        ForgotPasswordDoneBtn = new javax.swing.JButton();
        npwdLbl = new javax.swing.JLabel();
        cnpwdLbl = new javax.swing.JLabel();
        nsecqLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nsecqTF = new javax.swing.JTextField();
        nsecansTF = new javax.swing.JTextField();
        nsecansLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pwdPF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        ForgotPasswordBtn = new javax.swing.JButton();
        unameCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        ForgotPasswordDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ForgotPasswordDialog.setTitle("Answer security question");
        ForgotPasswordDialog.setModal(true);
        ForgotPasswordDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                ForgotPasswordDialogWindowClosed(evt);
            }
        });

        secqLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secqLbl.setText("What is your favourite colour ?");

        secansTF.setBackground(java.awt.Color.pink);
        secansTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secansTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                secansTFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                secansTFKeyAll(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secansTFKeyAll(evt);
            }
        });

        npwdPF.setBackground(java.awt.Color.pink);
        npwdPF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                npwdPFCaretUpdate(evt);
            }
        });
        npwdPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                secansTFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                npwdPFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secansTFKeyAll(evt);
            }
        });

        jLabel4.setText("New Password-");

        jLabel5.setText("Confirm new Password-");

        cnpwdPF.setBackground(java.awt.Color.pink);
        cnpwdPF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cnpwdPFCaretUpdate(evt);
            }
        });
        cnpwdPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnpwdPFKeyReleased(evt);
            }
        });

        ForgotPasswordDoneBtn.setText("Done");
        ForgotPasswordDoneBtn.setEnabled(false);
        ForgotPasswordDoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotPasswordDoneBtnActionPerformed(evt);
            }
        });

        npwdLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        npwdLbl.setText("0/45");

        cnpwdLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cnpwdLbl.setText("0/45");

        nsecqLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nsecqLbl.setText("0/100");

        jLabel10.setText("New security question-");

        nsecqTF.setBackground(java.awt.Color.pink);
        nsecqTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nsecqTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nsecqTFCaretUpdate(evt);
            }
        });
        nsecqTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nsecqTFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nsecqTFKeyAll(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nsecqTFKeyAll(evt);
            }
        });

        nsecansTF.setBackground(java.awt.Color.pink);
        nsecansTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nsecansTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nsecansTFCaretUpdate(evt);
            }
        });
        nsecansTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nsecansTFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nsecansTFKeyAll(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nsecansTFKeyAll(evt);
            }
        });

        nsecansLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nsecansLbl.setText("0/100");

        jLabel6.setText("Answer-");

        javax.swing.GroupLayout ForgotPasswordDialogLayout = new javax.swing.GroupLayout(ForgotPasswordDialog.getContentPane());
        ForgotPasswordDialog.getContentPane().setLayout(ForgotPasswordDialogLayout);
        ForgotPasswordDialogLayout.setHorizontalGroup(
            ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nsecansTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nsecqTF)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgotPasswordDialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgotPasswordDialogLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(256, 256, 256)
                                .addComponent(nsecqLbl))
                            .addComponent(nsecansLbl, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secansTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secqLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                                .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(npwdPF, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cnpwdPF, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(npwdLbl)
                                    .addComponent(cnpwdLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(ForgotPasswordDoneBtn)
                                .addGap(32, 32, 32)))))
                .addContainerGap())
        );
        ForgotPasswordDialogLayout.setVerticalGroup(
            ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secqLbl)
                .addGap(18, 18, 18)
                .addComponent(secansTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npwdPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForgotPasswordDialogLayout.createSequentialGroup()
                        .addComponent(npwdLbl)
                        .addGap(6, 6, 6)
                        .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cnpwdPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ForgotPasswordDoneBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cnpwdLbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nsecqTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForgotPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nsecqLbl))
                .addGap(7, 7, 7)
                .addComponent(nsecansTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nsecansLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Password-");

        pwdPF.setBackground(new java.awt.Color(204, 255, 204));
        pwdPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("Username-");

        LoginBtn.setBackground(new java.awt.Color(204, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        ForgotPasswordBtn.setBackground(new java.awt.Color(204, 255, 255));
        ForgotPasswordBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ForgotPasswordBtn.setText("Forgot Password");
        ForgotPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotPasswordBtnActionPerformed(evt);
            }
        });

        unameCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unameCBItemStateChanged(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\mysql-5.0.13-rc-win32\\java\\newlibrarymanagementsystem\\images\\scarey-black-white-book-skull-magic-animated-gif.gif")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("WELCOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LoginBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ForgotPasswordBtn))
                            .addComponent(pwdPF)
                            .addComponent(unameCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unameCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginBtn)
                    .addComponent(ForgotPasswordBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ForgotPasswordDialogreset(){
    secansTF.setText("");
    npwdPF.setText("");
    cnpwdPF.setText("");
    nsecqTF.setText("");
    nsecansTF.setText("");
    secansTF.setBackground(Color.pink);
    npwdPF.setBackground(Color.pink);
    cnpwdPF.setBackground(Color.pink);
    nsecqTF.setBackground(Color.pink);
    nsecansTF.setBackground(Color.pink);
    ForgotPasswordDoneBtn.setEnabled(false);
    }
    
    public void ForgotPasswordrefresh(){
        boolean key1 = false;
        boolean key2 = false;
        boolean key3 = false;
        boolean key4 = false;
        
        {
        String inp = secansTF.getText();
        if(inp.equals(""))
        secansTF.setBackground(Color.pink);
    else {
    secansTF.setBackground(Color.white);
    key1 = true;
    }
        {
    String inp1 = new String(npwdPF.getPassword());
    String inp2 = new String(cnpwdPF.getPassword());
    if(inp1.equals("") || inp1.length()>45){
    npwdPF.setBackground(Color.pink);
    cnpwdPF.setBackground(Color.pink);
    }
    else{
        if(inp1.equals(inp2)){
    npwdPF.setBackground(Color.white);
    cnpwdPF.setBackground(Color.white);
    key2 = true;
        }
        else{
        npwdPF.setBackground(Color.pink);
    cnpwdPF.setBackground(Color.pink);
        }
    }
    }
        }
        {
        String inp = nsecansTF.getText();
        if(inp.length()>100){
            inp = inp.substring(0,100);
            nsecansTF.setText(inp);
        }
        boolean pass = false;
        for(int i=0 ; i<inp.length() ; i++)
            if((int)inp.charAt(i)!=32)
                pass = true;
        if(pass){
        nsecansTF.setBackground(Color.white);
        key3 = true;
    }
        else{
        nsecansTF.setBackground(Color.pink);
        }
        }
        {
        String inp = nsecqTF.getText();
        if(inp.length()>100){
            inp = inp.substring(0,100);
            nsecqTF.setText(inp);
        }
        boolean pass = false;
        for(int i=0 ; i<inp.length() ; i++)
            if((int)inp.charAt(i)!=32)
                pass = true;
        if(pass){
        nsecqTF.setBackground(Color.white);
        key4 = true;
    }
        else{
        nsecqTF.setBackground(Color.pink);
        }
        }
        
        if(key1 && key2 && key3 && key4)
            ForgotPasswordDoneBtn.setEnabled(true);
        else ForgotPasswordDoneBtn.setEnabled(false);
    }
    
    private void ForgotPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPasswordBtnActionPerformed
        // TODO add your handling code here:
        ForgotPasswordDialog.pack();
        ForgotPasswordDialog.setLocationRelativeTo(null);
        ForgotPasswordDialog.setVisible(true);
    }//GEN-LAST:event_ForgotPasswordBtnActionPerformed

    private void npwdPFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_npwdPFCaretUpdate
        // TODO add your handling code here:
        npwdLbl.setText(npwdPF.getPassword().length+"/45");
    }//GEN-LAST:event_npwdPFCaretUpdate

    private void cnpwdPFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cnpwdPFCaretUpdate
        // TODO add your handling code here:
        cnpwdLbl.setText(cnpwdPF.getPassword().length+"/45");
    }//GEN-LAST:event_cnpwdPFCaretUpdate

    private void secansTFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secansTFKeyAll
        // TODO add your handling code here:
        ForgotPasswordrefresh();
    }//GEN-LAST:event_secansTFKeyAll

    private void npwdPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npwdPFKeyReleased
        // TODO add your handling code here:
        ForgotPasswordrefresh();
    }//GEN-LAST:event_npwdPFKeyReleased

    private void cnpwdPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnpwdPFKeyReleased
        // TODO add your handling code here:
        ForgotPasswordrefresh();
    }//GEN-LAST:event_cnpwdPFKeyReleased

    private void ForgotPasswordDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ForgotPasswordDialogWindowClosed
        // TODO add your handling code here:
        ForgotPasswordDialogreset();
    }//GEN-LAST:event_ForgotPasswordDialogWindowClosed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        String unamep = unameCB.getSelectedItem().toString();
        String pwdp = new String(pwdPF.getPassword());
        String uname = Newlibrarymanagementsystem.MysqlEscapeSeq(unamep);
        String pwd = Newlibrarymanagementsystem.MysqlEscapeSeq(pwdp);
        String query = "SELECT * FROM accounts WHERE uname = \'"+uname+"\' AND pwd = \'"+pwd+"\' ORDER BY uname DESC ;" ;
    try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
    ResultSet rs = stmt.executeQuery(query);
    if(rs.next()){
    new MenuFrame(uname,pwd).setVisible(true);
    this.dispose();
    JOptionPane.showMessageDialog(null,"Logged in successfully");
    }
    else{
        JOptionPane.showMessageDialog(null,"Incorrect password");
        WrongPasswordCounter++;
        pwdPF.setText("");
        if(WrongPasswordCounter>2)
            ForgotPasswordBtn.setVisible(true);
        pwdPF.requestFocus();
    }
    }
    catch(Exception e){
        System.out.println(e);
    }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void unameCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unameCBItemStateChanged
        // TODO add your handling code here:
        pwdPF.setText("");
        ForgotPasswordBtn.setVisible(false);
        WrongPasswordCounter = 0;
    }//GEN-LAST:event_unameCBItemStateChanged

    private void nsecqTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nsecqTFCaretUpdate
        // TODO add your handling code here:
        nsecqLbl.setText(nsecqTF.getText().length()+"/100");
    }//GEN-LAST:event_nsecqTFCaretUpdate

    private void nsecqTFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nsecqTFKeyAll
        // TODO add your handling code here:
        ForgotPasswordrefresh();
    }//GEN-LAST:event_nsecqTFKeyAll

    private void nsecansTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nsecansTFCaretUpdate
        // TODO add your handling code here:
        nsecansLbl.setText(nsecansTF.getText().length()+"/100");
    }//GEN-LAST:event_nsecansTFCaretUpdate

    private void nsecansTFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nsecansTFKeyAll
        // TODO add your handling code here:
        ForgotPasswordrefresh();
    }//GEN-LAST:event_nsecansTFKeyAll

    private void ForgotPasswordDoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPasswordDoneBtnActionPerformed
        // TODO add your handling code here:
        String uname = Newlibrarymanagementsystem.MysqlEscapeSeq(unameCB.getSelectedItem().toString());
        String secans = Newlibrarymanagementsystem.MysqlEscapeSeq(secansTF.getText());
        String query = "SELECT * FROM accounts WHERE uname = '"+uname+"' AND secans = '"+secans+"' ;"  ;
         try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
    ResultSet rs = stmt.executeQuery(query);
    if(rs.next()){
    String npwd = Newlibrarymanagementsystem.MysqlEscapeSeq(new String(npwdPF.getPassword()));
        String nsecq = Newlibrarymanagementsystem.MysqlEscapeSeq(nsecqTF.getText());
        String nsecans = Newlibrarymanagementsystem.MysqlEscapeSeq(nsecansTF.getText());
        
        query = "UPDATE accounts SET pwd = '"+npwd+"', secq = '"+nsecq+"', secans = '"+nsecans+"' WHERE uname = '"+uname+"' ;" ;
        stmt= (com.mysql.jdbc.Statement) c.createStatement();
        stmt.executeUpdate(query);
        rs.close();
        stmt.close();
        c.close();
        JOptionPane.showMessageDialog(null,"Account info changed");
        ForgotPasswordDialog.dispatchEvent(new WindowEvent(ForgotPasswordDialog, WindowEvent.WINDOW_CLOSING));
        pwdPF.setText("");
        pwdPF.requestFocus();
    }
    else {
        rs.close();
        stmt.close();
        c.close();
        JOptionPane.showMessageDialog(null,"Wrong answer");
         }
    }
         catch(Exception e){
             System.out.println(e);
         }
        
        
        String npwd = Newlibrarymanagementsystem.MysqlEscapeSeq(new String(npwdPF.getPassword()));
        String nsecq = Newlibrarymanagementsystem.MysqlEscapeSeq(nsecqTF.getText());
        String nsecans = Newlibrarymanagementsystem.MysqlEscapeSeq(nsecansTF.getText());
        
    }//GEN-LAST:event_ForgotPasswordDoneBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ForgotPasswordBtn;
    private javax.swing.JDialog ForgotPasswordDialog;
    private javax.swing.JButton ForgotPasswordDoneBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel cnpwdLbl;
    private javax.swing.JPasswordField cnpwdPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel npwdLbl;
    private javax.swing.JPasswordField npwdPF;
    private javax.swing.JLabel nsecansLbl;
    private javax.swing.JTextField nsecansTF;
    private javax.swing.JLabel nsecqLbl;
    private javax.swing.JTextField nsecqTF;
    private javax.swing.JPasswordField pwdPF;
    private javax.swing.JTextField secansTF;
    private javax.swing.JLabel secqLbl;
    private javax.swing.JComboBox<String> unameCB;
    // End of variables declaration//GEN-END:variables
}
