/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newlibrarymanagementsystem;

import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhavesh
 */
public class RegisteredStudentsFrame extends javax.swing.JFrame {

    MenuFrame mnfobj;
    /**
     * Creates new form RegisteredStudentsFrame
     */
    public RegisteredStudentsFrame(MenuFrame mnfobj) {
        initComponents();
        this.mnfobj = mnfobj;
        this.setLocationRelativeTo(null);
    }
    
    public String CBIndexToColName(int i){
        String colname=null;
    switch(i){
        case 0: colname = "CONV(sid,10,18)";
        break;
        case 1: colname = "rno";
        break;
        case 2: colname = "name";
        break;
        case 3: colname = "gender";
        break;
        case 4: colname = "fname";
        break;
        case 5: colname = "cno";
        break;
        case 6: colname = "address";
        break;
    }
    return colname;
    }
    
    public void refresh(){
        RemoveStudentBtn.setEnabled(false);
    String sfield1 = CBIndexToColName(SearchFieldCB1.getSelectedIndex());
    String sfield2 = CBIndexToColName(SearchFieldCB2.getSelectedIndex());
    String sfield3 = CBIndexToColName(SearchFieldCB3.getSelectedIndex());
    String scrit1 = (String)SearchCritCB1.getSelectedItem();
    String scrit2 = (String)SearchCritCB2.getSelectedItem();
    String scrit3 = (String)SearchCritCB3.getSelectedItem();
    String search1 = Newlibrarymanagementsystem.MysqlEscapeSeq(SearchTF1.getText());
    String search2 = Newlibrarymanagementsystem.MysqlEscapeSeq(SearchTF2.getText());
    String search3 = Newlibrarymanagementsystem.MysqlEscapeSeq(SearchTF3.getText());  
    
    boolean inv1 = NOTCheck1.isSelected();
    boolean inv2 = NOTCheck2.isSelected();
    boolean inv3 = NOTCheck3.isSelected();
    String sorter = CBIndexToColName(SortCB.getSelectedIndex());
    if(sorter.equals("CONV(sid,10,18)"))
        sorter = "sid" ;
    boolean sortdesc = SortDescCheck.isSelected();
    String query = "SELECT CONV(sid,10,18),rno,name,gender,fname,cno,address FROM students WHERE "+(inv1 ? "NOT " : "")+sfield1+" "+(scrit1.length()==1 ? scrit1 : "LIKE")+" \'"+(scrit1=="ends with" || scrit1=="includes" ? "%" : "")+search1+(scrit1=="starts with" || scrit1=="includes" ? "%" : "")+"\' AND "+(inv2 ? "NOT " : "")+sfield2+" "+(scrit2.length()==1 ? scrit2 : "LIKE")+" \'"+(scrit2=="ends with" || scrit2=="includes" ? "%" : "")+search2+(scrit2=="starts with" || scrit2=="includes" ? "%" : "")+"\' AND "+(inv3 ? "NOT " : "")+sfield3+" "+(scrit3.length()==1 ? scrit3 : "LIKE")+" \'"+(scrit3=="ends with" || scrit3=="includes" ? "%" : "")+search3+(scrit3=="starts with" || scrit3=="includes" ? "%" : "")+"\' ORDER BY "+sorter+(sortdesc ? " DESC " : " ")+";" ;
    DefaultTableModel model = (DefaultTableModel)Tbl.getModel();
    int rows = model.getRowCount();
    if(rows!=0)
        for(int i=0 ; i<rows ; i++)
            model.removeRow(0);
    try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
    ResultSet rs = stmt.executeQuery(query);
    Object[] tuple = new Object[7];
    while(rs.next()){
    for(int i=1 ; i<=7; i++)
    tuple[i-1] = rs.getObject(i);
    model.addRow(tuple);
    }
    rs.close();
    stmt.close();
    c.close();
    }
    catch(Exception e){
        System.out.println(e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStudentDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        name1TF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        name2TF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        name1Lbl = new javax.swing.JLabel();
        name2Lbl = new javax.swing.JLabel();
        name3TF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        name3Lbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rnoTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cnoTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        fname1TF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        fname2TF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fname1Lbl = new javax.swing.JLabel();
        fname2Lbl = new javax.swing.JLabel();
        fname3TF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        fname3Lbl = new javax.swing.JLabel();
        rnoLbl = new javax.swing.JLabel();
        cnoLbl = new javax.swing.JLabel();
        MaleRB = new javax.swing.JRadioButton();
        FemaleRB = new javax.swing.JRadioButton();
        addressLbl = new javax.swing.JLabel();
        AddStudentDoneBtn = new javax.swing.JButton();
        GenderBtnGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        SortDescCheck = new javax.swing.JCheckBox();
        AddStudentBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl = new javax.swing.JTable();
        SortCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchFieldCB1 = new javax.swing.JComboBox<>();
        SearchTF1 = new javax.swing.JTextField();
        SearchFieldCB2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SearchFieldCB3 = new javax.swing.JComboBox<>();
        SearchCritCB2 = new javax.swing.JComboBox<>();
        SearchCritCB1 = new javax.swing.JComboBox<>();
        SearchCritCB3 = new javax.swing.JComboBox<>();
        SearchTF2 = new javax.swing.JTextField();
        SearchTF3 = new javax.swing.JTextField();
        NOTCheck1 = new javax.swing.JCheckBox();
        NOTCheck2 = new javax.swing.JCheckBox();
        NOTCheck3 = new javax.swing.JCheckBox();
        RemoveStudentBtn = new javax.swing.JButton();

        AddStudentDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddStudentDialog.setTitle("Add New Student");
        AddStudentDialog.setAlwaysOnTop(true);
        AddStudentDialog.setResizable(false);
        AddStudentDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                AddStudentDialogWindowClosed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Student's details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        name1TF.setBackground(java.awt.Color.pink);
        name1TF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                name1TFCaretUpdate(evt);
            }
        });
        name1TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name1TFKeyAll(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name1TFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name1TFKeyAll(evt);
            }
        });

        jLabel8.setText("First-");

        name2TF.setBackground(java.awt.Color.lightGray);
        name2TF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                name2TFCaretUpdate(evt);
            }
        });
        name2TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name2TFKeyAll(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name2TFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name2TFKeyAll(evt);
            }
        });

        jLabel9.setText("Middle-");

        name1Lbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        name1Lbl.setText("0/15");

        name2Lbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        name2Lbl.setText("0/15");

        name3TF.setBackground(java.awt.Color.pink);
        name3TF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                name3TFCaretUpdate(evt);
            }
        });
        name3TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name3TFKeyAll(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name3TFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name3TFKeyAll(evt);
            }
        });

        jLabel10.setText("Last-");

        name3Lbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        name3Lbl.setText("0/15");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name1Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(name1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(name2Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(name3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name3Lbl)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name3Lbl)
                .addGap(59, 59, 59))
        );

        jLabel5.setText("Roll no-");

        rnoTF.setBackground(java.awt.Color.pink);
        rnoTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                rnoTFCaretUpdate(evt);
            }
        });
        rnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rnoTFKeyAll(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rnoTFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rnoTFKeyAll(evt);
            }
        });

        jLabel6.setText("Contact no-");

        cnoTF.setBackground(java.awt.Color.pink);
        cnoTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cnoTFCaretUpdate(evt);
            }
        });
        cnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnoTFKeyAll(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnoTFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnoTFKeyAll(evt);
            }
        });

        jLabel7.setText("Address-");

        addressTF.setBackground(java.awt.Color.pink);
        addressTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                addressTFCaretUpdate(evt);
            }
        });
        addressTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressTFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTFKeyAll(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressTFKeyAll(evt);
            }
        });

        jLabel14.setText("Gender-");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Father's Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        fname1TF.setBackground(java.awt.Color.pink);
        fname1TF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fname1TFCaretUpdate(evt);
            }
        });
        fname1TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fname1TFKeyAll(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fname1TFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fname1TFKeyAll(evt);
            }
        });

        jLabel21.setText("First-");

        fname2TF.setBackground(java.awt.Color.lightGray);
        fname2TF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fname2TFCaretUpdate(evt);
            }
        });
        fname2TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fname2TFKeyAll(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fname2TFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fname2TFKeyAll(evt);
            }
        });

        jLabel22.setText("Middle-");

        fname1Lbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        fname1Lbl.setText("0/15");

        fname2Lbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        fname2Lbl.setText("0/15");

        fname3TF.setBackground(java.awt.Color.pink);
        fname3TF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fname3TFCaretUpdate(evt);
            }
        });
        fname3TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fname3TFKeyAll(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fname3TFKeyAll(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fname3TFKeyAll(evt);
            }
        });

        jLabel25.setText("Last-");

        fname3Lbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        fname3Lbl.setText("0/15");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fname2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fname1Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fname1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fname2Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fname3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fname3Lbl)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fname1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fname2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fname3Lbl)
                .addGap(59, 59, 59))
        );

        rnoLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        rnoLbl.setText("0/5");

        cnoLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cnoLbl.setText("0/10");

        GenderBtnGroup.add(MaleRB);
        MaleRB.setSelected(true);
        MaleRB.setText("Male");

        GenderBtnGroup.add(FemaleRB);
        FemaleRB.setText("Female");

        addressLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        addressLbl.setText("0/100");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addressLbl, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(addressTF))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rnoLbl))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cnoLbl)))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MaleRB)
                                .addComponent(FemaleRB))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(rnoLbl))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cnoLbl)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MaleRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FemaleRB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressLbl))
        );

        AddStudentDoneBtn.setText("Done");
        AddStudentDoneBtn.setEnabled(false);
        AddStudentDoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentDoneBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddStudentDialogLayout = new javax.swing.GroupLayout(AddStudentDialog.getContentPane());
        AddStudentDialog.getContentPane().setLayout(AddStudentDialogLayout);
        AddStudentDialogLayout.setHorizontalGroup(
            AddStudentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentDialogLayout.createSequentialGroup()
                .addGroup(AddStudentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddStudentDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddStudentDialogLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(AddStudentDoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddStudentDialogLayout.setVerticalGroup(
            AddStudentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddStudentDoneBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registered Students");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        SortDescCheck.setSelected(true);
        SortDescCheck.setText("in descending order");
        SortDescCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SortDescCheckItemStateChanged(evt);
            }
        });

        AddStudentBtn.setText("Add Student");
        AddStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentBtnActionPerformed(evt);
            }
        });

        Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1234", "12345", "123456789012345678901234567890123456789012345", "1", "123456789012345678901234567890123456789012345", "1234567890", "1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Id.", "Roll no.", "Name", "Gender", "Father's name", "Contact no.", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl.setCellSelectionEnabled(true);
        Tbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tbl.getTableHeader().setReorderingAllowed(false);
        Tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TblMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl);
        if (Tbl.getColumnModel().getColumnCount() > 0) {
            Tbl.getColumnModel().getColumn(0).setPreferredWidth(40);
            Tbl.getColumnModel().getColumn(1).setPreferredWidth(20);
            Tbl.getColumnModel().getColumn(2).setPreferredWidth(230);
            Tbl.getColumnModel().getColumn(3).setPreferredWidth(20);
            Tbl.getColumnModel().getColumn(4).setPreferredWidth(230);
            Tbl.getColumnModel().getColumn(5).setPreferredWidth(45);
            Tbl.getColumnModel().getColumn(6).setPreferredWidth(300);
        }

        SortCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Id.", "Roll no.", "Name", "Gender", "Father's name", "Contact no.", "Address" }));
        SortCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SortCBItemStateChanged(evt);
            }
        });

        jLabel4.setText("Sort by");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Criteria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("1");

        SearchFieldCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Id.", "Roll no.", "Name", "Gender", "Father's name", "Contact no.", "Address" }));
        SearchFieldCB1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchFieldCB1ItemStateChanged(evt);
            }
        });

        SearchTF1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                SearchTF1CaretUpdate(evt);
            }
        });

        SearchFieldCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Id.", "Roll no.", "Name", "Gender", "Father's name", "Contact no.", "Address" }));
        SearchFieldCB2.setSelectedItem("Roll no.");
        SearchFieldCB2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchFieldCB2ItemStateChanged(evt);
            }
        });

        jLabel2.setText("2");

        jLabel3.setText("3");

        SearchFieldCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Id.", "Roll no.", "Name", "Gender", "Father's name", "Contact no.", "Address" }));
        SearchFieldCB3.setSelectedItem("Name");
        SearchFieldCB3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchFieldCB3ItemStateChanged(evt);
            }
        });

        SearchCritCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "starts with", "ends with", "includes" }));
        SearchCritCB2.setSelectedItem("starts with");
        SearchCritCB2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchCritCB2ItemStateChanged(evt);
            }
        });

        SearchCritCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "starts with", "ends with", "includes" }));
        SearchCritCB1.setSelectedItem("starts with");
        SearchCritCB1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchCritCB1ItemStateChanged(evt);
            }
        });

        SearchCritCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "starts with", "ends with", "includes" }));
        SearchCritCB3.setSelectedItem("starts with");
        SearchCritCB3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchCritCB3ItemStateChanged(evt);
            }
        });

        SearchTF2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                SearchTF2CaretUpdate(evt);
            }
        });

        SearchTF3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                SearchTF3CaretUpdate(evt);
            }
        });

        NOTCheck1.setText("NOT");
        NOTCheck1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NOTCheck1ItemStateChanged(evt);
            }
        });

        NOTCheck2.setText("NOT");
        NOTCheck2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NOTCheck2ItemStateChanged(evt);
            }
        });

        NOTCheck3.setText("NOT");
        NOTCheck3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NOTCheck3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SearchFieldCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchFieldCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchFieldCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NOTCheck3)
                            .addComponent(NOTCheck1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchCritCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(SearchTF1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchCritCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(SearchTF3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NOTCheck2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchCritCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(SearchTF2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(SearchFieldCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NOTCheck1)
                            .addComponent(SearchCritCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchFieldCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(SearchCritCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NOTCheck2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchFieldCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchCritCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NOTCheck3))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        RemoveStudentBtn.setText("Remove Student");
        RemoveStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveStudentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(AddStudentBtn)
                                .addGap(38, 38, 38)
                                .addComponent(RemoveStudentBtn)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(SortCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SortDescCheck)
                                .addGap(17, 17, 17)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SortDescCheck)
                            .addComponent(SortCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveStudentBtn)
                            .addComponent(AddStudentBtn)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void AddStudentDialogreset(){
    name1TF.setText("");
    name2TF.setText("");
    name3TF.setText("");
    fname1TF.setText("");
    fname2TF.setText("");
    fname3TF.setText("");
    rnoTF.setText("");
    cnoTF.setText("");
    addressTF.setText("");
    MaleRB.setSelected(true);
    name1TF.setBackground(Color.pink);
    name2TF.setBackground(Color.LIGHT_GRAY);
    name3TF.setBackground(Color.pink);
    fname1TF.setBackground(Color.pink);
    fname2TF.setBackground(Color.LIGHT_GRAY);
    fname3TF.setBackground(Color.pink);
    rnoTF.setBackground(Color.pink);
    cnoTF.setBackground(Color.pink);
    addressTF.setBackground(Color.pink);
    AddStudentDoneBtn.setEnabled(false);
    }
    
    public void AddStudentDialogrefresh(){
    boolean key1 = false;
    boolean key2 = false;
    boolean key3 = false;
    boolean key4 = false;
    boolean key5 = false;
    boolean key6 = false;
    boolean key7 = false;
    boolean key8 = false;
    boolean key9 = false;
    
    {
    String inp = name1TF.getText().toUpperCase();
    if(inp.length()>15)
        inp = inp.substring(0,15);
    name1TF.setText(inp);
    boolean pass = true;
    if(inp.length()==0)
        pass = false;
    for(int i=0 ; i<inp.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<65 || charcod>90)
        pass = false;
    }
    if(pass){
    name1TF.setBackground(Color.white);
    key1 = true;
    }
    else name1TF.setBackground(Color.pink);
    }
    {
    String inp = name2TF.getText().toUpperCase();
    if(inp.length()>15)
        inp = inp.substring(0,15);
    name2TF.setText(inp);
    boolean pass = true;
    if(inp.length()==0){
        name2TF.setBackground(Color.LIGHT_GRAY);
        key2 = true;
        pass = false;
    }
    for(int i=0 ; i<inp.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<65 || charcod>90)
        pass = false;
    }
    if(pass){
    name2TF.setBackground(Color.white);
    key2 = true;
    }
    else if(key2==false)
        name2TF.setBackground(Color.pink);
    }
    {
    String inp = name3TF.getText().toUpperCase();
    if(inp.length()>15)
        inp = inp.substring(0,15);
    name3TF.setText(inp);
    boolean pass = true;
    if(inp.length()==0)
        pass = false;
    for(int i=0 ; i<inp.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<65 || charcod>90)
        pass = false;
    }
    if(pass){
    name3TF.setBackground(Color.white);
    key3 = true;
    }
    else name3TF.setBackground(Color.pink);
    }
    {
    String inp = fname1TF.getText().toUpperCase();
    if(inp.length()>15)
        inp = inp.substring(0,15);
    fname1TF.setText(inp);
    boolean pass = true;
    if(inp.length()==0)
        pass = false;
    for(int i=0 ; i<inp.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<65 || charcod>90)
        pass = false;
    }
    if(pass){
    fname1TF.setBackground(Color.white);
    key4 = true;
    }
    else fname1TF.setBackground(Color.pink);
    }
    {
    String inp = fname2TF.getText().toUpperCase();
    if(inp.length()>15)
        inp = inp.substring(0,15);
    fname2TF.setText(inp);
    boolean pass = true;
    if(inp.length()==0){
    fname2TF.setBackground(Color.LIGHT_GRAY);
        key5 = true;
        pass = false;
    }
    for(int i=0 ; i<inp.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<65 || charcod>90)
        pass = false;
    }
    if(pass){
    fname2TF.setBackground(Color.white);
    key5 = true;
    }
    else if(key5==false)
        fname2TF.setBackground(Color.pink);
    }
    {
    String inp = fname3TF.getText().toUpperCase();
    if(inp.length()>15)
        inp = inp.substring(0,15);
    fname3TF.setText(inp);
    boolean pass = true;
    if(inp.length()==0)
        pass = false;
    for(int i=0 ; i<inp.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<65 || charcod>90)
        pass = false;
    }
    if(pass){
    fname3TF.setBackground(Color.white);
    key6 = true;
    }
    else fname3TF.setBackground(Color.pink);
    }
    {
    String inp = cnoTF.getText().toUpperCase();
    if(inp.length()>10)
        inp = inp.substring(0,10);
    cnoTF.setText(inp);
    boolean pass = true;
    if(inp.length()==0)
        pass = false;
    for(int i=0 ; i<inp.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<48 || charcod>57)
        pass = false;
    }
    if(pass){
    cnoTF.setBackground(Color.white);
    key7 = true;
    }
    else cnoTF.setBackground(Color.pink);
    }
    {
    String inp = addressTF.getText();
    if(inp.length()>100)
        inp = inp.substring(0,100);
    addressTF.setText(inp);
    boolean pass = false;
    if(inp.length()==0)
        pass = false;
    for(int i=0 ; i<inp.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod!=32)
        pass = true;
    }
    if(pass){
    addressTF.setBackground(Color.white);
    key8 = true;
    }
    else addressTF.setBackground(Color.pink);
    }
    {
    String inp = rnoTF.getText().toUpperCase();
    if(inp.length()>5)
        inp = inp.substring(0,5);
    rnoTF.setText(inp);
    String tests = inp;
    if(inp.length()!=5)
        rnoTF.setBackground(Color.pink);
    else {
    int seccod = (int)tests.charAt(4);
    if(seccod<65 || seccod>90)
        rnoTF.setBackground(Color.pink);
    else {
        tests = tests.substring(0,4);
        if(tests.substring(2,4).equals("XX")){
            tests = tests.substring(0,2);
        boolean pass = true;
    for(int i=0 ; i<tests.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<48 || charcod>57)
        pass = false;
        }
    if(pass){
        int classnum = Integer.parseInt(tests);
        if(classnum>0 && classnum<13){
        rnoTF.setBackground(Color.white);
        key9 = true;
        }
        else rnoTF.setBackground(Color.pink);
    }
    else rnoTF.setBackground(Color.pink);
        }
        else{
        boolean pass = true;
    for(int i=0 ; i<tests.length() ; i++){
    int charcod = (int)inp.charAt(i);
    if(charcod<48 || charcod>57)
        pass = false;
        }
    if(pass){
    int rnonum = Integer.parseInt(tests);
    if(rnonum>100 && rnonum<1300 && rnonum%100!=0){
    String query = "SELECT * FROM students WHERE rno = \'"+inp+"\' ;" ;
    try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
    ResultSet rs = stmt.executeQuery(query);
if(rs.next())
    rnoTF.setBackground(Color.orange);
else {
rnoTF.setBackground(Color.white);
key9 = true;
}
rs.close();
    stmt.close();
    c.close();
    }
    catch(Exception e){
        System.out.println(e);
    }
    }
    else rnoTF.setBackground(Color.pink);
    }
    else rnoTF.setBackground(Color.pink);
        }
    }
    }
    }
    
    if(key1 && key2 && key3 && key4 && key5 && key6 && key7 && key8 && key9)
            AddStudentDoneBtn.setEnabled(true);
        else AddStudentDoneBtn.setEnabled(false);
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        mnfobj.studbtnen();
    }//GEN-LAST:event_formWindowClosed

    private void AddStudentDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AddStudentDialogWindowClosed
        // TODO add your handling code here:
        AddStudentDialogreset();
        mnfobj.setEnabled(true);
        this.setEnabled(true);
        this.requestFocus();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddStudentDialogWindowClosed

    private void AddStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentBtnActionPerformed
        // TODO add your handling code here:
        mnfobj.setEnabled(false);
        AddStudentDialog.pack();
        AddStudentDialog.setVisible(true);
        this.setEnabled(false);
        AddStudentDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddStudentBtnActionPerformed

    private void SortDescCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SortDescCheckItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SortDescCheckItemStateChanged

    private void SortCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SortCBItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SortCBItemStateChanged

    private void SearchTF1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_SearchTF1CaretUpdate
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchTF1CaretUpdate

    private void SearchTF2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_SearchTF2CaretUpdate
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchTF2CaretUpdate

    private void SearchTF3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_SearchTF3CaretUpdate
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchTF3CaretUpdate

    private void SearchCritCB1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchCritCB1ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchCritCB1ItemStateChanged

    private void SearchCritCB2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchCritCB2ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchCritCB2ItemStateChanged

    private void SearchCritCB3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchCritCB3ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchCritCB3ItemStateChanged

    private void NOTCheck1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NOTCheck1ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_NOTCheck1ItemStateChanged

    private void NOTCheck2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NOTCheck2ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_NOTCheck2ItemStateChanged

    private void NOTCheck3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NOTCheck3ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_NOTCheck3ItemStateChanged

    private void SearchFieldCB1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchFieldCB1ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchFieldCB1ItemStateChanged

    private void SearchFieldCB2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchFieldCB2ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchFieldCB2ItemStateChanged

    private void SearchFieldCB3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchFieldCB3ItemStateChanged
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_SearchFieldCB3ItemStateChanged

    private void TblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblMouseReleased
        // TODO add your handling code here:
        if(Tbl.getSelectedRowCount()>0)
            RemoveStudentBtn.setEnabled(true);
        else RemoveStudentBtn.setEnabled(false);
    }//GEN-LAST:event_TblMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_formWindowOpened

    private void name1TFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_name1TFCaretUpdate
        // TODO add your handling code here:
        name1Lbl.setText(name1TF.getText().length()+"/15");
    }//GEN-LAST:event_name1TFCaretUpdate

    private void name2TFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_name2TFCaretUpdate
        // TODO add your handling code here:
        name2Lbl.setText(name2TF.getText().length()+"/15");
    }//GEN-LAST:event_name2TFCaretUpdate

    private void name3TFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_name3TFCaretUpdate
        // TODO add your handling code here:
        name3Lbl.setText(name3TF.getText().length()+"/15");
    }//GEN-LAST:event_name3TFCaretUpdate

    private void fname1TFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fname1TFCaretUpdate
        // TODO add your handling code here:
        fname1Lbl.setText(fname1TF.getText().length()+"/15");
    }//GEN-LAST:event_fname1TFCaretUpdate

    private void fname2TFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fname2TFCaretUpdate
        // TODO add your handling code here:
        fname2Lbl.setText(fname2TF.getText().length()+"/15");
    }//GEN-LAST:event_fname2TFCaretUpdate

    private void fname3TFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fname3TFCaretUpdate
        // TODO add your handling code here:
        fname3Lbl.setText(fname3TF.getText().length()+"/15");
    }//GEN-LAST:event_fname3TFCaretUpdate

    private void rnoTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_rnoTFCaretUpdate
        // TODO add your handling code here:
        rnoLbl.setText(rnoTF.getText().length()+"/5");
    }//GEN-LAST:event_rnoTFCaretUpdate

    private void cnoTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cnoTFCaretUpdate
        // TODO add your handling code here:
        cnoLbl.setText(cnoTF.getText().length()+"/10");
    }//GEN-LAST:event_cnoTFCaretUpdate

    private void addressTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_addressTFCaretUpdate
        // TODO add your handling code here:
        addressLbl.setText(addressTF.getText().length()+"/100");
    }//GEN-LAST:event_addressTFCaretUpdate

    private void name1TFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name1TFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_name1TFKeyAll

    private void name2TFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name2TFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_name2TFKeyAll

    private void name3TFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name3TFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_name3TFKeyAll

    private void fname1TFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fname1TFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_fname1TFKeyAll

    private void fname2TFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fname2TFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_fname2TFKeyAll

    private void fname3TFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fname3TFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_fname3TFKeyAll

    private void rnoTFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rnoTFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_rnoTFKeyAll

    private void cnoTFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnoTFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_cnoTFKeyAll

    private void addressTFKeyAll(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTFKeyAll
        // TODO add your handling code here:
        AddStudentDialogrefresh();
    }//GEN-LAST:event_addressTFKeyAll

    private void AddStudentDoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentDoneBtnActionPerformed
        // TODO add your handling code here:
        String[] indata = new String[10];
        indata[0] = rnoTF.getText();
        indata[1] = name1TF.getText();
        indata[2] = name2TF.getText();
        indata[3] = name3TF.getText();
        indata[4] = fname1TF.getText();
        indata[5] = fname2TF.getText();
        indata[6] = fname3TF.getText();
        indata[7] = cnoTF.getText();
        indata[8] = Newlibrarymanagementsystem.MysqlEscapeSeq(addressTF.getText());
        indata[9] = (MaleRB.isSelected() ? "M" : "F");
        
        indata[1] = (indata[1].charAt(0)+indata[1].substring(1,indata[1].length()).toLowerCase()+" ");
        indata[3] = (indata[3].charAt(0)+indata[3].substring(1,indata[3].length()).toLowerCase());
        indata[4] = (indata[4].charAt(0)+indata[4].substring(1,indata[4].length()).toLowerCase()+" ");
        indata[6] = (indata[6].charAt(0)+indata[6].substring(1,indata[6].length()).toLowerCase());
        if(indata[2].equals("")){}
        else indata[2] = (indata[2].charAt(0)+indata[2].substring(1,indata[2].length()).toLowerCase()+" ");
        if(indata[5].equals("")){}
        else indata[5] = (indata[5].charAt(0)+indata[5].substring(1,indata[5].length()).toLowerCase()+" ");
        
        String query = "INSERT INTO students (rno,name,fname,cno,address,gender) VALUES('"+indata[0]+"','"+indata[1]+indata[2]+indata[3]+"','"+indata[4]+indata[5]+indata[6]+"',"+indata[7]+",'"+indata[8]+"','"+indata[9]+"') ;" ;
        try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
            stmt.executeUpdate(query);
            stmt= (com.mysql.jdbc.Statement) c.createStatement();
            query = "INSERT INTO evl VALUES(NOW(),'Student "+indata[0]+" added. Name- "+indata[1]+indata[2]+indata[3]+"','"+mnfobj.LoggedInUserName+"') ;" ;
            stmt.executeUpdate(query);
            stmt.close();
    c.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        
        AddStudentDialog.dispatchEvent(new WindowEvent(AddStudentDialog, WindowEvent.WINDOW_CLOSING));
        refresh();
        mnfobj.evlrefresh();
        
    }//GEN-LAST:event_AddStudentDoneBtnActionPerformed

    private void RemoveStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveStudentBtnActionPerformed
        // TODO add your handling code here:
        String sid = Tbl.getValueAt(Tbl.getSelectedRow(),0).toString();
               sid = (""+Integer.parseInt(sid,18));
        boolean pass = true;
        {
        String query = "SELECT * FROM issues WHERE sid = '"+sid+"' ;" ;
        try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            if(rs.next()){
            pass = false;
            }
            rs.close();
            stmt.close();
            c.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        }
        if(pass){
        int choice = JOptionPane.showConfirmDialog(null,"Remove selected student ?");
        if(choice==JOptionPane.YES_OPTION){
        String rno = Tbl.getValueAt(Tbl.getSelectedRow(),1).toString();
        String name = Tbl.getValueAt(Tbl.getSelectedRow(),2).toString();
        
        String query = "DELETE FROM students WHERE sid = '"+sid+"' ;" ;
        try{
    Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/newlibman";
            Connection c=DriverManager.getConnection(url,"root","123");
            com.mysql.jdbc.Statement stmt= (com.mysql.jdbc.Statement) c.createStatement();
            stmt.executeUpdate(query);
            stmt= (com.mysql.jdbc.Statement) c.createStatement();
            query = "INSERT INTO evl VALUES(NOW(),'Student "+rno+" removed. Name- "+name+"','"+mnfobj.LoggedInUserName+"') ;" ;
            stmt.executeUpdate(query);
            stmt.close();
    c.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        
        refresh();
        mnfobj.evlrefresh();
        }
        }
        else JOptionPane.showMessageDialog(null,"This student has issued book(s)");
    }//GEN-LAST:event_RemoveStudentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisteredStudentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisteredStudentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisteredStudentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisteredStudentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudentBtn;
    private javax.swing.JDialog AddStudentDialog;
    private javax.swing.JButton AddStudentDoneBtn;
    private javax.swing.JRadioButton FemaleRB;
    private javax.swing.ButtonGroup GenderBtnGroup;
    private javax.swing.JRadioButton MaleRB;
    private javax.swing.JCheckBox NOTCheck1;
    private javax.swing.JCheckBox NOTCheck2;
    private javax.swing.JCheckBox NOTCheck3;
    private javax.swing.JButton RemoveStudentBtn;
    private javax.swing.JComboBox<String> SearchCritCB1;
    private javax.swing.JComboBox<String> SearchCritCB2;
    private javax.swing.JComboBox<String> SearchCritCB3;
    private javax.swing.JComboBox<String> SearchFieldCB1;
    private javax.swing.JComboBox<String> SearchFieldCB2;
    private javax.swing.JComboBox<String> SearchFieldCB3;
    private javax.swing.JTextField SearchTF1;
    private javax.swing.JTextField SearchTF2;
    private javax.swing.JTextField SearchTF3;
    private javax.swing.JComboBox<String> SortCB;
    private javax.swing.JCheckBox SortDescCheck;
    private javax.swing.JTable Tbl;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTF;
    private javax.swing.JLabel cnoLbl;
    private javax.swing.JTextField cnoTF;
    private javax.swing.JLabel fname1Lbl;
    private javax.swing.JTextField fname1TF;
    private javax.swing.JLabel fname2Lbl;
    private javax.swing.JTextField fname2TF;
    private javax.swing.JLabel fname3Lbl;
    private javax.swing.JTextField fname3TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name1Lbl;
    private javax.swing.JTextField name1TF;
    private javax.swing.JLabel name2Lbl;
    private javax.swing.JTextField name2TF;
    private javax.swing.JLabel name3Lbl;
    private javax.swing.JTextField name3TF;
    private javax.swing.JLabel rnoLbl;
    private javax.swing.JTextField rnoTF;
    // End of variables declaration//GEN-END:variables
}
